### ISSUE TITLE
scala:cc miscompiles

### ISSUE THREAD

**Issue by DemiMarie** [davidB/scala-maven-plugin#203] opened 2017-03-15 23:39 UTC
When I run `mvn scala:cc` on a project (sorry, can't provide the code – it's a homework assignment), loading the resulting class files into Apache Spark gives a `java.lang.NoSuchMethodError`, presumably due to the classes being compiled for the wrong version of Scala.

**Comment by davidB** [comment] 2017-03-16 16:23
Right, the cause is a mismatch between runtime classpath and compile time
classpath (without the stacktrace it's impossible to say if it's wrong
scala version or something else)

Can you provide the full StackTrace of the error ?

**Comment by slandelle** [comment] 2019-02-24 23:21
Been idle without any info for too long, closing.

**Closed by slandelle** 2019-02-24 23:21 UTC
