### ISSUE TITLE
Not support java 16 record

### ISSUE THREAD

**Issue by cmonkey** [davidB/scala-maven-plugin#521] opened 2021-10-18 02:53 UTC
alchim31 scala plugin version : 4.5.3 
java version 16
recompileMode = incremental 
compileOrder = Mixed 

ca Example.java 
record Example(int id, double amount){}

compile failed : illegal start of type declaration

**Comment by slandelle** [comment] 2021-10-18 08:32
Please provide a sample project and push it on github.

**Comment by slandelle** [comment] 2021-10-18 12:10
Thx.

The Scala compiler doesn't support Java records yet.
According to https://github.com/scala/bug/issues/11908, support should land in 2.13.7, which hasn't been released yet.
According to [this ticket](https://contributors.scala-lang.org/t/scala-2-13-7-release-planning/5221/2), the ETA is beginning of November.

Anyway, closing as the issue is not in this plugin.

**Closed as completed by slandelle** 2021-10-18 12:10 UTC

**Comment by EleanoraKotarski1968** [comment] 2021-11-01 19:03
Same thing here

**Comment by slandelle** [comment] 2021-11-02 00:49
Scala 2.13.7 was just released today. Try upgrading.
