### ISSUE TITLE
Trying to use latest version 4.5.1 with scala version 2.12 , mvn build is getting failed with error

### ISSUE THREAD

**Issue by munkumar** [davidB/scala-maven-plugin#474] opened 2021-05-12 14:52 UTC
/var/folders/n5/0krr9f7n1s3bn74mdhsc0gwmmm2b31/T/scala-maven-plugin-compiler-bridge-sources5832050757105567612/scala/ZincCompat.scala:19: error: type PlainNioFile is not a member of package scala.reflect.io
  type PlainNioFile = scala.reflect.io.PlainNioFile
                                       ^
/var/folders/n5/0krr9f7n1s3bn74mdhsc0gwmmm2b31/T/scala-maven-plugin-compiler-bridge-sources5832050757105567612/scala/ZincCompat.scala:23: error: type mismatch;
 found   : pf.type (with underlying type scala.ZincCompat.PlainNioFile)
 required: ?{def getClass: ?}
    val f = pf.getClass.getDeclaredField("nioPath") // it's not val'd in 2.12 :-/

using the version 4.5.1 with scala version 2.12, executing mvn clean install -U command throwing error
Kindly help to understand and resolve the issue .
            ^

**Comment by davidB** [comment] 2021-05-12 17:02
With version 4.5.x I change the way to build classloader. It's strange that this error was not raise by integration testing. Can you provide us a small/minimal project sample that reproduce the bug ?

**Comment by munkumar** [comment] 2021-05-12 18:02
The issue is coming for version like 4.4.1 as well with scala 2.12 version

Can you help me which version of plugin is compatible and ideally i should use 2.12.3 scala version ?


I used below mvn script in pom.xml to build my project ( a spark with java and scala support )

 <maven.compiler.plugin.version>3.8.0</maven.compiler.plugin.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <scala.version>2.12</scala.version>
        <scala.min.version>2.12.0</scala.min.version>


<plugin>
                <groupId>net.alchim31.maven</groupId>
                <artifactId>scala-maven-plugin</artifactId>
                <version>4.5.1</version>
                <executions>
                    <execution>
                        <id>scala-compile-first</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>add-source</goal>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>scala-test-compile</id>
                        <phase>process-test-resources</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

**Comment by munkumar** [comment] 2021-05-12 18:09
Although with version 3.4.6 and scala version 2.11 working fine.

**Comment by davidB** [comment] 2021-05-13 13:11
Sorry, the fragment of pom.xml  provided is not enough to help us to debug or to reproduce the issue. without "reproducible" case we can't investigate and help you.

PS, please enclosed your code or log between triple backquote to be more readable (and preserve indentation,...).

**Comment by davidB** [comment] 2021-05-23 19:25
A min difference between 3.x and 4.x is that since 4.x the default compilation mode switch from `all` (in 3.x) to `incremental` (in 4.x).
Can you tell us if you have the issue with `4.5.2` (released this week-end) with

```xml
    <configuration>
      <recompileMode>incremental</recompileMode>
    </configuration>
```

and with

```xml
    <configuration>
      <recompileMode>all</recompileMode>
    </configuration>
```

**Comment by davidB** [comment] 2021-06-13 09:01
Without more info, I close this issue.
Feel free to reopen with complementary information to help debug.

**Closed by davidB** 2021-06-13 09:01 UTC

**Comment by davidrabinowitz** [comment] 2022-12-20 22:38
I have a repro case in https://github.com/GoogleCloudDataproc/spark-bigquery-connector/pull/841, compile with `./mvnw install -Pdsv1_2.12`. Can you please re-open the issue?

**Comment by slandelle** [comment] 2022-12-20 22:46
@davidrabinowitz 2 things:
* Your project is using scala-maven-plugin 4.4.0. The latest version of this plugin is 4.8.0. The first ting you must try is upgrading.
* Your project is way too large to investigate. Please provide a simple reproducer as described here: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by davidrabinowitz** [comment] 2022-12-20 23:01
Thanks for the fast response! The referenced PR is the upgrade to version 4.8.0 that fails with this issue's error. I'll try to have a simpler project
