### ISSUE TITLE
scaladoc for submodule support

### ISSUE THREAD

**Issue by lanking520** [davidB/scala-maven-plugin#278] opened 2018-07-11 22:58 UTC
Hi,

I am trying to use the `Scaladoc` plugin to generate javadoc jar on Maven. I have a big project contains several modules in Maven. However I see that plugin will generate the javadoc in each of the submodule but not wrapping it up together at one place. I created a assembly stage to combine all of the jar files to the same place but it seemed not working.

**Comment by lanking520** [comment] 2018-07-11 23:03
#222

**Comment by slandelle** [comment] 2020-05-14 00:08
Closing as duplicate of #222

**Closed by slandelle** 2020-05-14 00:08 UTC
