### ISSUE TITLE
Could not transfer artifact org.sonatype.oss:oss-parent:pom:7 from/to scala-tools.org 

### ISSUE THREAD

**Issue by echoqu** [davidB/scala-maven-plugin#188] opened 2016-04-18 09:47 UTC
spark-bench
 ./build-all.sh 

[ERROR] Plugin net.alchim31.maven:scala-maven-plugin:3.2.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for net.alchim31.maven:scala-maven-plugin:jar:3.2.0: Could not transfer artifact org.sonatype.oss:oss-parent:pom:7 from/to scala-tools.org (https://oss.sonatype.org/content/groups/scala-tools/): Connection to http://172.17.18.80:8080 refused: Connection timed out -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
Build failed, please check!

**Comment by davidB** [comment] 2016-04-18 11:55
Hi,

Can you provide more information ? like 
* the pom.xml fragment with all the configuration of
  * the scala-maven-plugin
  * the repositories and the plugin-repositories
* what/where is the maven command (build-all.sh is not a command from this project) ?
* can you run with -e and share the full stack trace ?
* Any info that can help me to reproduce (I'm not a spark user or dev).

Else I don't understand why there is a dependency to scala-tools.org (especialy for org.sonatype.oss:oss-parent)

**Comment by slandelle** [comment] 2019-02-24 23:24
Looks like a network issue. Closing.

**Closed by slandelle** 2019-02-24 23:24 UTC
