### ISSUE TITLE
doc-jar goal can't get correct dependency

### ISSUE THREAD

**Issue by wangyum** [davidB/scala-maven-plugin#320] opened 2019-02-22 14:26 UTC
`mvn package` build success, but `mvn install` always build failure with ```error: not found: type AsyncFrameBuffer```.
How to reproduce:
```shell
$ git clone https://github.com/wangyum/spark.git && cd spark && git checkout CARMEL-363
$ build/mvn install -DskipTests -Phive -Phadoop-3.1 # Install dependency first
$ build/mvn install -DskipTests -pl sql/hive-thriftserver2  -Phive-thriftserver2 -Phadoop-3.1 # throw exception
$ build/mvn package -DskipTests -pl sql/hive-thriftserver2  -Phive-thriftserver2 -Phadoop-3.1 # build success
```
If [remove doc-jar goal](https://github.com/wangyum/spark/blob/e7343735b59dfc21e61bea9d4619adf09982a10f/pom.xml#L2188-L2194). install can build success:
```shell
$ build/mvn install -DskipTests -pl sql/hive-thriftserver2  -Phive-thriftserver2 -Phadoop-3.1 # build success after remove doc-jar goal
```

**Comment by davidB** [comment] 2019-02-24 14:16
Hi,

When I look at `spark/sql/hive-thriftserver2/src/gen/java/org/apache/hive/service/rpc/thrift/TCLIService.java` I don't see definition of `AsyncFrameBuffer` in the file (no import) or in the directory.

What should be the missing dependency ?

Can you provide an small isolated project that reproduce the issue ?

**Comment by wangyum** [comment] 2019-02-25 05:18
Thanks @davidB. It can not recognize inner class. It works after this commit:
https://github.com/wangyum/spark/commit/638c47fabaaa1a07dad9a7a2a376e02cb7551046

**Comment by davidB** [comment] 2019-02-25 09:46
So you can close this ticket ?

**Comment by wangyum** [comment] 2019-02-25 09:54
I think it's a bug. I'm just workaround it, but did not fix it. right?

**Comment by davidB** [comment] 2019-02-25 10:05
from your workaround it doesn't looks like a dependency bug (related to classpath), but to a bug inside `scala` compiler. I'll take another look.

**Closed** 2019-02-25 10:31 UTC
